Ui.cpp: always use "%s"-style format for printf()-style functions
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    Ui.cpp:293:16: error: format not a string literal and no format arguments [-Werror=format-security]
      293 |       mvwprintw(w,0,0,msg.c_str());
          |       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~

Let's wrap all the missing places with "%s" format.